[package]
name = "devshare-helper"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
description = "The part of DevShare that needs administrator rights on a guest's computer"

[[bin]]
name = "devshare-helper"
path = "src/main.rs"

[dependencies]
devshare-protocol = { workspace = true, features = ["certificates"] }
anyhow.workspace = true
base64 = "0.22"
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap = { version = "4", features = ["derive"] }
tun = "0.8"
nix = { version = "0.31", features = ["socket", "uio", "fs", "user"] }
